version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: campusvibe-db
    environment:
      POSTGRES_DB: campusvibe
      POSTGRES_USER: arpan
      POSTGRES_PASSWORD: password
    ports:
      - "5332:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arpan"]
      interval: 10s
      timeout: 5s
      retries: 5

  s3:
    image: adobe/s3mock:3.1.0
    container_name: campusvibe-s3
    ports:
      - "9090:9090"
    environment:
      - initialBuckets=campusvibe-clubs,campusvibe-events,campusvibe-customer

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: campusvibe-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/campusvibe
      SPRING_DATASOURCE_USERNAME: arpan
      SPRING_DATASOURCE_PASSWORD: password
      AWS_S3_MOCK: "true"
      AWS_REGION: us-east-1
      AWS_S3_BUCKET_CLUBS: campusvibe-clubs
      AWS_S3_BUCKET_EVENTS: campusvibe-events
      AWS_S3_BUCKET_CUSTOMER: campusvibe-customer
      # Add GOOGLE_CLIENT_ID if needed
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_started
    volumes:
      - ../backend:/app

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    container_name: campusvibe-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../frontend:/app

volumes:
  db_data:
