// Mock/static data for development and fallback
import { EventInstance, Club } from "@/app/types";

export const popularEvents: EventInstance[] = [
  {
    id: 1,
    title: "ReMode, Circular Fashion Festival | Festival de Mode...",
    description: "A festival celebrating circular fashion and sustainability.",
    dateTime: new Date("2025-09-28T12:00:00"),
    createdAt: new Date("2025-09-01T09:00:00"),
    location: "Society for Arts and Technology [SAT]",
    price: "Free",
    organizer: "fashion-takes-action",
    followers: 137,
    images: ["/frosh1.jpeg"],
    promoted: true,
    capacity: 200,
    registered: 100,
    categories: ["Dating", "Research", "Food"]
  },
  {
    id: 2,
    title: "Montreal Tech Summit 2025",
    description: "Annual summit for tech enthusiasts and professionals.",
    dateTime: new Date("2025-10-06T09:00:00"),
    createdAt: new Date("2025-09-10T09:00:00"),
    location: "Palais des congrès de Montréal",
    price: "Paid",
    organizer: "tech-montreal",
    followers: 520,
    images: ["/frosh2.jpeg"],
    promoted: false,
    capacity: 500,
    registered: 400,
    categories: ["Dating", "Research", "Food"]
  },
  {
    id: 3,
    title: "Art Expo Montreal",
    description: "Showcase of local and international artists.",
    dateTime: new Date("2025-10-18T11:00:00"),
    createdAt: new Date("2025-09-15T09:00:00"),
    location: "Montreal Art Centre",
    price: "Free",
    organizer: "montreal-artists",
    followers: 260,
    images: ["/party.jpg"],
    promoted: false,
    capacity: 300,
    registered: 100,
    categories: ["Dating", "Research", "Food"]
  },
  {
    id: 4,
    title: "Startup Pitch Night",
    description: "Pitch your startup ideas to investors.",
    dateTime: new Date("2025-11-03T18:00:00"),
    createdAt: new Date("2025-09-20T09:00:00"),
    location: "Notman House",
    price: "Free",
    organizer: "startup-montreal",
    followers: 420,
    images: ["/pixel.jpg"],
    promoted: false,
    capacity: 150,
    registered: 120,
    categories: ["Dating", "Research", "Food"]
  },
  {
    id: 5,
    title: "Startup Pitch Night",
    description: "Pitch your startup ideas to investors.",
    dateTime: new Date("2025-11-03T18:00:00"),
    createdAt: new Date("2025-09-20T09:00:00"),
    location: "Notman House",
    price: "Free",
    organizer: "startup-montreal",
    followers: 420,
    images: ["/birthday-party.jpg"],
    promoted: false,
    capacity: 150,
    registered: 120,
    categories: ["Dating", "Research", "Food"]
  },
  {
    id: 6,
    title: "Startup Pitch Night",
    description: "Pitch your startup ideas to investors.",
    dateTime: new Date("2025-11-03T18:00:00"),
    createdAt: new Date("2025-09-20T09:00:00"),
    location: "Notman House",
    price: "Free",
    organizer: "startup-montreal",
    followers: 420,
    images: ["/food.jpg"],
    promoted: false,
    capacity: 150,
    registered: 120,
    categories: ["Nightlife"]
  },
  {
    id: 7,
    title: "Startup Pitch Night",
    description: "Pitch your startup ideas to investors.",
    dateTime: new Date("2025-11-03T18:00:00"),
    createdAt: new Date("2025-09-20T09:00:00"),
    location: "Notman House",
    price: "Free",
    organizer: "startup-montreal",
    followers: 420,
    images: ["/colors.jpg"],
    promoted: false,
    capacity: 150,
    registered: 120,
    categories: ["Tech", "Networking"]
  },
  {
    id: 8,
    title: "Startup Pitch Night",
    description: "Pitch your startup ideas to investors.",
    dateTime: new Date("2025-11-03T18:00:00"),
    createdAt: new Date("2025-09-20T09:00:00"),
    location: "Notman House",
    price: "Free",
    organizer: "startup-montreal",
    followers: 420,
    images: ["/rave.jpg"],
    promoted: false,
    capacity: 150,
    registered: 120,
    categories: ["Tech", "Networking"]
  },
];

export const clubs: Club[] = [
  {
    id: "fashion-takes-action",
    name: "Fashion Takes Action",
    description: "A student-run organization dedicated to promoting sustainable fashion practices and raising awareness about the environmental and social impacts of the fashion industry.",
    followers: 130,
    logo: "/frosh1.jpeg",
    socialLinks: {
      email: "",
      website: "",
      facebook: "",
      instagram: "",
    },
    featured: true,
    images: ["/frosh1.jpeg"],
    createdAt: new Date("2025-08-01T09:00:00"),
  },
  {
    id: "rib-entertainment",
    name: "RIB ENTERTAINMENT",
    description: "A student-run organization dedicated to promoting sustainable fashion practices and raising awareness about the environmental and social impacts of the fashion industry.",
    followers: 380,
    logo: "/frosh1.jpeg",
    socialLinks: {
      email: "",
      website: "",
      facebook: "",
      instagram: "",
    },
    featured: true,
    images: ["/frosh1.jpeg"],
    createdAt: new Date("2025-08-01T09:00:00"),
  },
  {
    id: "startup-montreal",
    name: "Making Waves Montreal",
    description: "A student-run organization dedicated to promoting sustainable fashion practices and raising awareness about the environmental and social impacts of the fashion industry.",
    followers: 174,
    logo: "/frosh2.jpeg",
    socialLinks: {
      email: "",
      website: "",
      facebook: "",
      instagram: "",
    },
    featured: true,
    images: ["/frosh2.jpeg"],
    createdAt: new Date("2025-08-01T09:00:00"),
  },
  {
    id: "tech-montreal",
    name: "PersianEvents",
    description: "A student-run organization dedicated to promoting sustainable fashion practices and raising awareness about the environmental and social impacts of the fashion industry.",
    followers: 128,
    logo: "/party.jpg",
    socialLinks: {
      email: "",
      website: "",
      facebook: "",
      instagram: "",
    },
    featured: true,
    images: ["/party.jpg"],
    createdAt: new Date("2025-08-01T09:00:00"),
  },
  {
    id: "montreal-artists",
    name: "Glimmering Dolls",
    description: "A student-run organization dedicated to promoting sustainable fashion practices and raising awareness about the environmental and social impacts of the fashion industry.",
    followers: 341,
    logo: "/pixel.jpg",
    socialLinks: {
      email: "",
      website: "",
      facebook: "",
      instagram: "",
    },
    featured: true,
    images: ["/pixel.jpg"],
    createdAt: new Date("2025-08-01T09:00:00"),
  }
];
