 // Mock/static data (or fetch here if SSR/ISR)

 export const popularEvents = [
  {
    id: 1,
    title: "ReMode, Circular Fashion Festival | Festival de Mode...",
    date: "Sun, Sep 28, 12:00 PM",
    location: "Society for Arts and Technology [SAT]",
    price: "Free",
    organizer: "Fashion Takes Action",
    followers: 137,
    image: "/frosh1.jpeg",
    promoted: true,
    capacity: 200,
    registered: 100,
    dateTime: "2025-09-20T12:00:00",
  },
  {
    id: 2,
    title: "Montreal Tech Summit 2025",
    date: "Mon, Oct 6, 9:00 AM",
    location: "Palais des congrès de Montréal",
    price: "Paid",
    organizer: "Tech Montreal",
    followers: 520,
    image: "/frosh2.jpeg",
    promoted: false,
    capacity: 500,
    registered: 400,
    dateTime: "2025-10-06T09:00:00",
  },
  {
    id: 3,
    title: "Art Expo Montreal",
    date: "Sat, Oct 18, 11:00 AM",
    location: "Montreal Art Centre",
    price: "Free",
    organizer: "Montreal Artists",
    followers: 260,
    image: "/events/event3.jpg",
    promoted: false,
    capacity: 300,
    registered: 100,
    dateTime: "2025-10-18T11:00:00",
  },
  {
    id: 4,
    title: "Startup Pitch Night",
    date: "Fri, Nov 3, 6:00 PM",
    location: "Notman House",
    price: "Free",
    organizer: "Startup Montreal",
    followers: 420,
    image: "/events/event4.jpg",
    promoted: false,
    capacity: 150,
    registered: 120,
    dateTime: "2025-10-18T11:00:00",
  },
  {
    id: 5,
    title: "Startup Pitch Night",
    date: "Fri, Nov 3, 6:00 PM",
    location: "Notman House",
    price: "Free",
    organizer: "Startup Montreal",
    followers: 420,
    image: "/events/event4.jpg",
    promoted: false,
    capacity: 150,
    registered: 120,
    dateTime: "2025-10-18T11:00:00",
  },
  {
    id: 6,
    title: "Startup Pitch Night",
    date: "Fri, Nov 3, 6:00 PM",
    location: "Notman House",
    price: "Free",
    organizer: "Startup Montreal",
    followers: 420,
    image: "/events/event4.jpg",
    promoted: false,
    capacity: 150,
    registered: 120,
    dateTime: "2025-10-18T11:00:00",
  },
  {
    id: 7,
    title: "Startup Pitch Night",
    date: "Fri, Nov 3, 6:00 PM",
    location: "Notman House",
    price: "Free",
    organizer: "Startup Montreal",
    followers: 420,
    image: "/events/event4.jpg",
    promoted: false,
    capacity: 150,
    registered: 120,
    dateTime: "2025-10-18T11:00:00",
  },
  {
    id: 8,
    title: "Startup Pitch Night",
    date: "Fri, Nov 3, 6:00 PM",
    location: "Notman House",
    price: "Free",
    organizer: "Startup Montreal",
    followers: 420,
    image: "/events/event4.jpg",
    promoted: false,
    capacity: 150,
    registered: 120,
    dateTime: "2025-10-18T11:00:00",
  },
];